pruebaAplicacionWebTarea1/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using System.Security.Claims;
using JassonContreras_TAREA1asp.net.Servicios;
using Clases_CRUD.CRUD_Modelos;

namespace JassonContreras_TAREA1asp.net.Controllers
{
    public class LoginController : Controller
    {
        private readonly ICliente servicioCliente;

        public LoginController(ICliente servicioCliente)
        {
            this.servicioCliente = servicioCliente;
        }
        public IActionResult Index()
        {   
           return View();
        }
      
        public IActionResult Validar()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Validar(Login login) //validamos el objeto login
        {
            Cliente usuario = await servicioCliente.ValidarLogin(login.Cedula, login.Contraseña);

            bool admin = true;

            if (usuario != null)
            {
                if (!login.Cedula.Equals("1-1111-1111"))
                {
                    admin = false;
                }

                var claims = new List<Claim> { //creamos un nuevo claims para el usuario

                    new Claim(ClaimTypes.Name,usuario.NombreCompleto),
                    new Claim(ClaimTypes.NameIdentifier, admin.ToString()),
                    new Claim("Contraseña", usuario.Contraseña),

                };

                foreach (string identificador in admin.ToString().Split('\u002C'))    //recorremos el objeto evaluando todas las cedulas
                {
                    claims.Add(new Claim(ClaimTypes.Role, identificador)); //guardamos en el claims el rol del usuario, y su cedula                    
                }

                var clainsIdentificacion = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme); //creamos una nueva autenticacion

                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(clainsIdentificacion)); //creamos su cookie respecito en memoria

                return RedirectToAction("Index", "Home");
            }
            ViewBag.result = "No existe ningun usuario con estas credenciales.";

            return View();
        }

        public async Task<IActionResult> Salir()//metodo para borrar el cokie creado por cada cliente registrado, esto con el fin de cerrar las vistas
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
            
        }       

    }
}

pruebaAplicacionWebTarea1/Controllers/ProveedoresController.cs
using Microsoft.AspNetCore.Mvc;

using Clases_CRUD.CRUD_Modelos;
using JassonContreras_TAREA1asp.net.Servicios;
using JassonContreras_TAREA1asp.net.Models;

namespace JassonContreras_TAREA1asp.net.Controllers
{
    public class ProveedoresController : Controller
    {

        private readonly IProvedor servicioProvedor;

        public ProveedoresController(IProvedor servicioProvedor)
        {
            this.servicioProvedor = servicioProvedor;
        }

        public async Task<ActionResult> Index()
        {
            var provedor = await servicioProvedor.ListaProvedor();

            if (provedor != null)
            {
                return View(provedor);
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Index(string buscar)
        {

            var filtroProvedor = await servicioProvedor.FiltroProvedorIndex(buscar);

            if (filtroProvedor != null)
            {
                return View(filtroProvedor);
            }
            else
            {
                var cliente = await servicioProvedor.ListaProvedor();

                return View(cliente);
            }

        }

        public IActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Crear(Provedor provedor)
        {

            var productoExiste = await servicioProvedor.CrearProvedor(provedor);

            if (productoExiste == null)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ViewBag.result = "Ya Existe un Usuario con Esta Cedula.";
                return View();
            }

        }
        public async Task<ActionResult> Editar(int Id)
        {
            if (Id == 0)
            {
                return View();
            }

            var provedor = await servicioProvedor.BuscarProvedorEditar(Id);

            if (provedor == null)
            {
                return View();
            }

            return View(provedor);
        }
        [HttpPost]
        public async Task<ActionResult> Editar(Provedor proveedores)
        {
            if (proveedores == null)
            {
                return View();
            }

            var provedorEditado = await servicioProvedor.EditarProvedor(proveedores);

            if (provedorEditado == null)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ViewBag.result = "Ya Existe un Usuario con Esta Cedula.";
                return View();
            }

        }

        public async Task<ActionResult> Eliminar(int Id)
        {

            if (Id == 0)
            {
                return View();
            }

            var provedor = await servicioProvedor.BuscarProvedorEliminar(Id);

            if (provedor == null)
            {
                return View();
            }
            return View(provedor);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Eliminar(int Id, Provedor proveedores)
        {
            var provedorBorrar = await servicioProvedor.EliminarProvedor(Id);

            if (provedorBorrar == null)
            {
                return RedirectToAction(nameof(Index));

            }
            return View();
        }



    }
}

pruebaAplicacionWebTarea1/Controllers/RegistroController.cs
using Microsoft.AspNetCore.Mvc;
using JassonContreras_TAREA1asp.net.Servicios;
using Clases_CRUD.CRUD_Modelos;

namespace JassonContreras_TAREA1asp.net.Controllers
{
    public class RegistroController : Controller
    {
        private readonly ICliente servicioCliente;

        public RegistroController(ICliente servicioCliente)
        {
            this.servicioCliente = servicioCliente;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult NuevoRegistro()
        {       
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> NuevoRegistro(Cliente nuevoCliente)//se ingresa el objeto cargado de la vista nuevo registro
        {
            if (nuevoCliente.Cedula == null || nuevoCliente.Telefono == 0 || nuevoCliente.CorreoElectronico == null || nuevoCliente.Contraseña == null || nuevoCliente.Profecion == null || nuevoCliente.FechaNacimiento == 0)
            {
                return View();
            }

            var existe = await servicioCliente.CrearUsuario(nuevoCliente);

            if (existe == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.result = "Ya Existe un Usuario con Esta Cedula.";
                return View();
            }

            
        }

    }
}

pruebaAplicacionWebTarea1/Controllers/ToursController.cs
using Microsoft.AspNetCore.Mvc;
using Clases_CRUD.CRUD_Modelos;
using JassonContreras_TAREA1asp.net.Servicios;


namespace JassonContreras_TAREA1asp.net.Controllers
{
    public class ToursController : Controller
    {
        static int lastId = 1;

        private readonly ITours servicioTours;

        public ToursController(ITours servicioTours)
        {
            this.servicioTours = servicioTours;
        }

        public async Task<ActionResult> Index()
        {
            var tours = await servicioTours.ListaTours();

            if (tours != null)
            {
                return View(tours);
            }
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Index(string buscar)
        {

            var filtroTours = await servicioTours.FiltroToursIndex(buscar);

            if (filtroTours != null)
            {
                return View(filtroTours);
            }
            else
            {
                var tours = await servicioTours.ListaTours();

                return View(tours);
            }

        }

        //static int generateId()
        //{
        //    return Interlocked.Increment(ref lastId);
        //}

        public async Task<ActionResult> Upsert(int Id)
        {
            var tors = await servicioTours.BuscarToursEditar(Id);

            if (tors != null)
            {
                return View(tors);
            }
            return View(new Tours { Id = 0 });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Upsert(int Id, Tours tours)
        {
            var files = HttpContext.Request.Form.Files;

            if (Id == 0)
            {
                //crear
                string upload = WC.ImagenRuta;
                string fileName = Guid.NewGuid().ToString();
                string extension = Path.GetExtension(files[0].FileName);

                using (var filesStream = new FileStream(Path.Combine(upload, fileName + extension), FileMode.Create))
                {
                    files[0].CopyTo(filesStream);
                }
                //tours.Id = generateId();
                tours.Imagen = fileName + extension;

                var creado = servicioTours.CrearTours(tours);

            }
            else
            {
                //actualizar

                var objProducto = await servicioTours.BuscarToursEditar(Id);

                if (files.Count > 0)
                {
                    string upload = WC.ImagenRuta;
                    string fileName = Guid.NewGuid().ToString();
                    string extension = Path.GetExtension(files[0].FileName);

                    //borrado del a imagen anterior

                    var anteriorFIle = Path.Combine(upload, objProducto.Imagen);

                    if (System.IO.File.Exists(anteriorFIle))
                    {
                        System.IO.File.Delete(anteriorFIle);
                    }

                    //finalizando el borrado de la imagen anterior

                    using (var filesStream = new FileStream(Path.Combine(upload, fileName + extension), FileMode.Create))
                    {
                        files[0].CopyTo(filesStream);
                    }
                    tours.Imagen = fileName + extension;
                }//caso contrario si el usuario no carga la imagen
                else
                {
                    tours.Imagen = objProducto.Imagen;
                }

                var edicion = await servicioTours.EditarTours(tours);

               
            }
            return RedirectToAction("Index","Home");

        }

        public async Task<ActionResult> Eliminar(int Id)
        {

            //if (Id == null)
            //{
            //    return View();
            //}

            var tours = await servicioTours.BuscarToursEliminar(Id);

            if (tours == null)
            {
                return View();
            }
            return View(tours);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Eliminar(int Id, Tours tours)
        {
            var toursBorrar = await servicioTours.EliminarTours(Id);

            if (toursBorrar == null)
            {
                return RedirectToAction(nameof(Index));

            }
            return View();
        }
    }

  }

pruebaAplicacionWebTarea1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Aplicacion Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/pruebaAplicacionWebTarea1.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TurismoCR</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index"><i class="fa-solid fa-house"></i> Inicio</a>
                        </li>
                        <br />
                        @if (User.IsInRole("True"))
                        {

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-white" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"> <i class="fa-regular fa-folder-open"></i> Registros Internos</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-area="" asp-controller="Producto" asp-action="Index">Producto <i class="fa-solid fa-truck-ramp-box"></i></a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Proveedores" asp-action="Index">Proveedores <i class="fa-solid fa-car"></i></a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Tours" asp-action="Index">Tours <i class="fa-sharp fa-solid fa-plane-departure"></i> </a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-area="" asp-controller="Login" asp-action="Salir">Cerrar Sesion <i class="fa-solid fa-right-to-bracket"></i></a>
                                </div>
                            </li>
                        }
                        @if (!User.IsInRole("True"))
                        {

                            <li class="nav-item">
                                <a class="nav-link text-dark text-white" asp-area="" asp-controller="Cliente" asp-action="Index">Cliente <i class="fa-regular fa-id-card"></i></a>
                            </li>
                        }

                        <li class="nav-item">
                            <a class="nav-link text-dark text-white" asp-area="" asp-controller="Facturacion" asp-action="Index">Facturacion <i class="fa-sharp fa-solid fa-paper-plane"></i> </a>
                        </li>

                        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">

                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Login" asp-action="Salir">
                                    Cerrar Sesion <i class="fa-solid fa-right-to-bracket"></i>
                                </a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Registro" asp-action="NuevoRegistro">
                                    Registrar <i class="fa-sharp fa-solid fa-user-plus"></i>
                                </a>
                            </li>

                            <li class="nav-item text-end">
                                <a class="nav-link text-white" asp-area="" asp-controller="Login" asp-action="Validar">
                                    Login <i class="fa-solid fa-circle-user"></i>
                                </a>
                            </li>

                        </ul>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

@*    <footer class="border-top footer text-muted bg-primary text-white-50">
        <div class="container">
            &copy; 2020 - SistemaInventario
        </div>
    </footer>*@

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://kit.fontawesome.com/0fe3b249ad.js" crossorigin="anonymous"></script>
    @*<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>*@
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>